1. 用subprocess来启动子进程和管理他们的输入和输出
2. 这种子进程是跟父进程（python解释器）并行执行的，能充分利用CPU的多核性能

- 子进程若终止，则返回returncode属性，否则即返回None
Popen.poll()


% python解释器进程
helios     10894  0.3  0.4 374092 69100 pts/1  0:00 /home/helios/anaconda3/envs/sleipnir/bin/python /home/helios/子命令.py
% 终端进程
helios     10896  0.0  0.0   4864   700 pts/1  0:00 /bin/sh -c roslaunch /home/helios/rviz.launch
% 命令行进程
helios     10897  0.7  0.2 297216 48276 pts/1  0:01 /usr/bin/python3 /opt/ros/noetic/bin/roslaunch /home/helios/rviz.launch
helios     10914 10.4  1.1 1908416 180144 ?    0:40 /home/helios/ws/Sleipnir/devel/lib/rviz/rviz /home/helios/test03.rviz __name:=rviz __log:=/home/helios/.ros/log/03230bd4-bd63-11eb-856d-63350de87134/rviz-1.log

线索
1. 使用proc.kill()并不会结束进程10894, 10986
2. kill掉10897 launch进程 能够进一步kill掉10914这个节点进程

helios     15467  3.6  0.4 598336 71336 pts/1  0:00 /home/helios/anaconda3/envs/sleipnir/bin/python /home/helios/子命令.py
helios     15482 12.9  1.1 1909760 179168 ?    0:05 /home/helios/ws/Sleipnir/devel/lib/rviz/rviz /home/helios/test03.rviz __name:=rviz __log:=/home/helios/.ros/log/03230bd4-bd63-11eb-856d-63350de87134/rviz-1.log



helios@helios:~$ ps -aux | grep 18942
helios     18942  2.3  0.9 3237336 155608 pts/1  Sl+  23:19   0:00 /home/helios/anaconda3/envs/sleipnir/bin/python /home/helios/ws/Sleipnir/src/gui/scripts/ui.py
helios     18980  0.0  0.0  14056   768 pts/6    S+   23:20   0:00 grep --color=auto 18942
helios@helios:~$ ps aux | grep 18812
helios     18991  0.0  0.0  14056   768 pts/6    S+   23:20   0:00 grep --color=auto 18812
helios@helios:~$ ps aux | grep 18907
helios     18907 13.3  2.1 3559160 357464 pts/1  Sl+  23:19   0:06 /home/helios/anaconda3/envs/sleipnir/bin/python /home/helios/ws/Sleipnir/src/gui/scripts/ui.py
helios     18995  0.0  0.0  14056   760 pts/6    S+   23:20   0:00 grep --color=auto 18907
helios@helios:~$ ps aux | grep 18956
helios     18956  1.0  0.4 743740 68588 ?        Ssl  23:19   0:00 python /home/helios/ws/Sleipnir/src/Sleipnir/control/script/stanley_medium_car.py __name:=control __log:=/home/helios/.ros/log/03230bd4-bd63-11eb-856d-63350de87134/control-1.log


In [3]:
import subprocess
subprocess.call("rqt&", shell=True)

0

In [3]:
a[0] =3 

NameError: name 'a' is not defined

In [3]:
class Solution:
    def maxCompatibilitySum(self, students, mentors) -> int:
        import numpy as np
        from scipy.optimize import linear_sum_assignment
        cost_matrix=[]
        for student in students:
            value_list=[]
            for mentor in mentors:
                temp_sum=0
                for i in range(len(student)):
                    if student[i]==mentor[i]:
                        temp_sum-=1
                value_list.append(temp_sum)
            cost_matrix.append(value_list)
        cost_mat_array=np.array(cost_matrix)
        print(cost_mat_array)
        row_ind,col_ind=linear_sum_assignment(cost_mat_array)
        return  int(cost_mat_array[row_ind, col_ind].sum())*(-1)

solution=Solution()
solution.maxCompatibilitySum(students=[[1,1,0],[1,0,1],[0,0,1]],mentors = [[1,0,0],[0,0,1],[1,1,0]])

[[-2  0 -3]
 [-2 -2 -1]
 [-1 -3  0]]


8